"""add foreign key to tags

Revision ID: f03b7dc8a6f4
Revises: 12ad88f74f47
Create Date: 2023-09-02 13:30:21.813800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f03b7dc8a6f4'
down_revision: Union[str, None] = '12ad88f74f47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_tags', sa.Column('task_id', sa.Integer(), nullable=True))
    op.add_column('task_tags', sa.Column('tag_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task_tags', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'task_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_tags', type_='foreignkey')
    op.drop_constraint(None, 'task_tags', type_='foreignkey')
    op.drop_column('task_tags', 'tag_id')
    op.drop_column('task_tags', 'task_id')
    # ### end Alembic commands ###
